// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhM4YDNfzj39fLstXIM_8QNzPBfulrZ8c',
    appId: '1:247682524509:web:fc682956afc08bd2f6b4b4',
    messagingSenderId: '247682524509',
    projectId: 'tasquest-abbad',
    authDomain: 'tasquest-abbad.firebaseapp.com',
    storageBucket: 'tasquest-abbad.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWNuLOQzmNaCD89Fvv3_MFU202KvGFW-w',
    appId: '1:247682524509:android:cda209e6921c36bff6b4b4',
    messagingSenderId: '247682524509',
    projectId: 'tasquest-abbad',
    storageBucket: 'tasquest-abbad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWz6lGz0DuUpSyNNrQoGW6cX1wUivgRZg',
    appId: '1:247682524509:ios:1cf8f83d18eef4f5f6b4b4',
    messagingSenderId: '247682524509',
    projectId: 'tasquest-abbad',
    storageBucket: 'tasquest-abbad.firebasestorage.app',
    iosBundleId: 'com.tasquest.tasquest',
  );
}
